# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baucua.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1436, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bau = QtWidgets.QPushButton(self.centralwidget)
        self.bau.setGeometry(QtCore.QRect(60, 30, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.bau.setFont(font)
        self.bau.setObjectName("bau")
        self.bau_label = QtWidgets.QLabel(self.centralwidget)
        self.bau_label.setGeometry(QtCore.QRect(100, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.bau_label.setFont(font)
        self.bau_label.setStyleSheet("color: rgb(82, 59, 255);")
        self.bau_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bau_label.setObjectName("bau_label")
        self.cua_label = QtWidgets.QLabel(self.centralwidget)
        self.cua_label.setGeometry(QtCore.QRect(340, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.cua_label.setFont(font)
        self.cua_label.setStyleSheet("color: rgb(82, 59, 255);")
        self.cua_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cua_label.setObjectName("cua_label")
        self.cua = QtWidgets.QPushButton(self.centralwidget)
        self.cua.setGeometry(QtCore.QRect(300, 30, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cua.setFont(font)
        self.cua.setObjectName("cua")
        self.tom_label = QtWidgets.QLabel(self.centralwidget)
        self.tom_label.setGeometry(QtCore.QRect(570, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.tom_label.setFont(font)
        self.tom_label.setStyleSheet("color: rgb(82, 59, 255);")
        self.tom_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tom_label.setObjectName("tom_label")
        self.tom = QtWidgets.QPushButton(self.centralwidget)
        self.tom.setGeometry(QtCore.QRect(530, 30, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.tom.setFont(font)
        self.tom.setObjectName("tom")
        self.ca_label = QtWidgets.QLabel(self.centralwidget)
        self.ca_label.setGeometry(QtCore.QRect(780, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.ca_label.setFont(font)
        self.ca_label.setStyleSheet("color: rgb(82, 59, 255);")
        self.ca_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ca_label.setObjectName("ca_label")
        self.ca = QtWidgets.QPushButton(self.centralwidget)
        self.ca.setGeometry(QtCore.QRect(740, 30, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.ca.setFont(font)
        self.ca.setObjectName("ca")
        self.ga_label = QtWidgets.QLabel(self.centralwidget)
        self.ga_label.setGeometry(QtCore.QRect(1000, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.ga_label.setFont(font)
        self.ga_label.setStyleSheet("color: rgb(82, 59, 255);")
        self.ga_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ga_label.setObjectName("ga_label")
        self.ga = QtWidgets.QPushButton(self.centralwidget)
        self.ga.setGeometry(QtCore.QRect(960, 30, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.ga.setFont(font)
        self.ga.setObjectName("ga")
        self.nail_label = QtWidgets.QLabel(self.centralwidget)
        self.nail_label.setGeometry(QtCore.QRect(1210, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.nail_label.setFont(font)
        self.nail_label.setStyleSheet("color: rgb(82, 59, 255);")
        self.nail_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nail_label.setObjectName("nail_label")
        self.nail = QtWidgets.QPushButton(self.centralwidget)
        self.nail.setGeometry(QtCore.QRect(1170, 30, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.nail.setFont(font)
        self.nail.setObjectName("nail")
        self.cua_kq = QtWidgets.QPushButton(self.centralwidget)
        self.cua_kq.setGeometry(QtCore.QRect(300, 410, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cua_kq.setFont(font)
        self.cua_kq.setObjectName("cua_kq")
        self.ga_label_kq = QtWidgets.QLabel(self.centralwidget)
        self.ga_label_kq.setGeometry(QtCore.QRect(1000, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.ga_label_kq.setFont(font)
        self.ga_label_kq.setStyleSheet("color: rgb(82, 59, 255);")
        self.ga_label_kq.setAlignment(QtCore.Qt.AlignCenter)
        self.ga_label_kq.setObjectName("ga_label_kq")
        self.tom_label_kq = QtWidgets.QLabel(self.centralwidget)
        self.tom_label_kq.setGeometry(QtCore.QRect(570, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.tom_label_kq.setFont(font)
        self.tom_label_kq.setStyleSheet("color: rgb(82, 59, 255);")
        self.tom_label_kq.setAlignment(QtCore.Qt.AlignCenter)
        self.tom_label_kq.setObjectName("tom_label_kq")
        self.nail_kq = QtWidgets.QPushButton(self.centralwidget)
        self.nail_kq.setGeometry(QtCore.QRect(1170, 410, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.nail_kq.setFont(font)
        self.nail_kq.setObjectName("nail_kq")
        self.nail_label_kq = QtWidgets.QLabel(self.centralwidget)
        self.nail_label_kq.setGeometry(QtCore.QRect(1210, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.nail_label_kq.setFont(font)
        self.nail_label_kq.setStyleSheet("color: rgb(82, 59, 255);")
        self.nail_label_kq.setAlignment(QtCore.Qt.AlignCenter)
        self.nail_label_kq.setObjectName("nail_label_kq")
        self.cua_label_kq = QtWidgets.QLabel(self.centralwidget)
        self.cua_label_kq.setGeometry(QtCore.QRect(340, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.cua_label_kq.setFont(font)
        self.cua_label_kq.setStyleSheet("color: rgb(82, 59, 255);")
        self.cua_label_kq.setAlignment(QtCore.Qt.AlignCenter)
        self.cua_label_kq.setObjectName("cua_label_kq")
        self.ca_label_kq = QtWidgets.QLabel(self.centralwidget)
        self.ca_label_kq.setGeometry(QtCore.QRect(780, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.ca_label_kq.setFont(font)
        self.ca_label_kq.setStyleSheet("color: rgb(82, 59, 255);")
        self.ca_label_kq.setAlignment(QtCore.Qt.AlignCenter)
        self.ca_label_kq.setObjectName("ca_label_kq")
        self.tom_kq = QtWidgets.QPushButton(self.centralwidget)
        self.tom_kq.setGeometry(QtCore.QRect(530, 410, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.tom_kq.setFont(font)
        self.tom_kq.setObjectName("tom_kq")
        self.bau_label_kq = QtWidgets.QLabel(self.centralwidget)
        self.bau_label_kq.setGeometry(QtCore.QRect(100, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.bau_label_kq.setFont(font)
        self.bau_label_kq.setStyleSheet("color: rgb(82, 59, 255);")
        self.bau_label_kq.setAlignment(QtCore.Qt.AlignCenter)
        self.bau_label_kq.setObjectName("bau_label_kq")
        self.ga_kq = QtWidgets.QPushButton(self.centralwidget)
        self.ga_kq.setGeometry(QtCore.QRect(960, 410, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.ga_kq.setFont(font)
        self.ga_kq.setObjectName("ga_kq")
        self.ca_kq = QtWidgets.QPushButton(self.centralwidget)
        self.ca_kq.setGeometry(QtCore.QRect(740, 410, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.ca_kq.setFont(font)
        self.ca_kq.setObjectName("ca_kq")
        self.bau_kq = QtWidgets.QPushButton(self.centralwidget)
        self.bau_kq.setGeometry(QtCore.QRect(60, 410, 181, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.bau_kq.setFont(font)
        self.bau_kq.setObjectName("bau_kq")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(240, 260, 311, 101))
        self.play_btn.setObjectName("play_btn")
        self.export_btn = QtWidgets.QPushButton(self.centralwidget)
        self.export_btn.setGeometry(QtCore.QRect(750, 260, 311, 101))
        self.export_btn.setObjectName("export_btn")
        self.bau.raise_()
        self.cua.raise_()
        self.tom.raise_()
        self.ca.raise_()
        self.ga.raise_()
        self.nail.raise_()
        self.ca_label.raise_()
        self.bau_label.raise_()
        self.cua_label.raise_()
        self.ga_label.raise_()
        self.nail_label.raise_()
        self.tom_label.raise_()
        self.cua_kq.raise_()
        self.nail_kq.raise_()
        self.nail_label_kq.raise_()
        self.tom_kq.raise_()
        self.ga_kq.raise_()
        self.ca_kq.raise_()
        self.bau_kq.raise_()
        self.bau_label_kq.raise_()
        self.cua_label_kq.raise_()
        self.ca_label_kq.raise_()
        self.tom_label_kq.raise_()
        self.ga_label_kq.raise_()
        self.play_btn.raise_()
        self.export_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1436, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bau.setText(_translate("MainWindow", "Bầu"))
        self.bau_label.setText(_translate("MainWindow", "0"))
        self.cua_label.setText(_translate("MainWindow", "0"))
        self.cua.setText(_translate("MainWindow", "Cua"))
        self.tom_label.setText(_translate("MainWindow", "0"))
        self.tom.setText(_translate("MainWindow", "Tôm"))
        self.ca_label.setText(_translate("MainWindow", "0"))
        self.ca.setText(_translate("MainWindow", "Cá"))
        self.ga_label.setText(_translate("MainWindow", "0"))
        self.ga.setText(_translate("MainWindow", "Gà"))
        self.nail_label.setText(_translate("MainWindow", "0"))
        self.nail.setText(_translate("MainWindow", "Nai"))
        self.cua_kq.setText(_translate("MainWindow", "Cua"))
        self.ga_label_kq.setText(_translate("MainWindow", "0"))
        self.tom_label_kq.setText(_translate("MainWindow", "0"))
        self.nail_kq.setText(_translate("MainWindow", "Nai"))
        self.nail_label_kq.setText(_translate("MainWindow", "0"))
        self.cua_label_kq.setText(_translate("MainWindow", "0"))
        self.ca_label_kq.setText(_translate("MainWindow", "0"))
        self.tom_kq.setText(_translate("MainWindow", "Tôm"))
        self.bau_label_kq.setText(_translate("MainWindow", "0"))
        self.ga_kq.setText(_translate("MainWindow", "Gà"))
        self.ca_kq.setText(_translate("MainWindow", "Cá"))
        self.bau_kq.setText(_translate("MainWindow", "Bầu"))
        self.play_btn.setText(_translate("MainWindow", "OK"))
        self.export_btn.setText(_translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

